# https://taskfile.dev
version: "3"
tasks:
  # brew install redis
  brewredislog: tail -f /opt/homebrew/var/log/redis.log
  pg: docker-compose exec postgres psql -U postgres
  mk-fair-db: docker-compose exec postgres psql -U postgres -c "create database zkfair_testnet"
  pg-fair: docker-compose exec postgres psql -U postgres zkfair_testnet
  pg-x1: docker-compose exec postgres psql -U postgres x1testnet

  rabbitlog: docker-compose logs -f rabbitmq
  rabbit: docker-compose exec rabbitmq bash

  redis: docker-compose exec redis redis-cli

  up:
    cmds:
      - docker-compose up -d
      - sleep 10 && task mk-fair-db
