# https://taskfile.dev
version: "3"
tasks:
  # brew install redis
  brewredislog: tail -f /opt/homebrew/var/log/redis.log
  pg: docker-compose exec postgres psql -U postgres
  mk-fair-db: docker-compose exec postgres psql -U postgres -c "create database zkfair_testnet"
  pg-fair: docker-compose exec postgres psql -U postgres zkfair_testnet
  mk-x1-db: docker-compose exec postgres psql -U postgres -c "create database indexer_x1_testnet"
  pg-x1: docker-compose exec postgres psql -U postgres indexer_x1_testnet

  redis: docker-compose exec redis redis-cli
  rabbitlog: docker-compose logs -f rabbitmq
  rabbitsh: docker-compose exec rabbitmq bash

  # setup
  up: docker-compose up -d
